CREATE TABLE IF NOT EXISTS t_commission (
	id INT(11) NOT NULL AUTO_INCREMENT,
	titre TEXT DEFAULT NULL,
	commissionnaire VARCHAR(50) DEFAULT NULL,
	montant DECIMAL(12,2) DEFAULT NULL,
	codeContrat VARCHAR(255) DEFAULT NULL,
	date DATE DEFAULT NULL,
	etat VARCHAR(50) DEFAULT NULL,
	status VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;